name: build

on:
  push:
    branches:
      - development-1.4.0
    paths:
      - 'src/main/java/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/main/java/**'

jobs:
  build-release:
    name: Build & Deploy Release
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      security-events: none
      packages: read
      actions: read
      contents: write

    strategy:
      fail-fast: true
      matrix:
        include:
          - language: java-kotlin
            build-mode: manual

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup JDK Temurin 21
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Display contents
        run: ls -a

      - name: Generate Version Number
        run: |
          VERSION=$(cat src/main/java/com/lgndluke/arearesetterpro/VERSION.DAT)
          VERSION="${VERSION}.${GITHUB_RUN_NUMBER}"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Display contents
        run: ls -a

      - name: Build Project
        run: |
          mvn install -f pom.xml -Drevision=${{ env.version }}
          mvn -B package -f pom.xml -Drevision=${{ env.version }}
          mkdir -p release
          mv target/AreaResetterPro*.jar release/

      - name: Display contents
        run: ls -a

      - name: Deploy Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: AreaResetterPro-${{ env.version }}
          name: AreaResetterPro-${{ env.version }}
          target_commitish: main
          generate_release_notes: true
          append_body: true
          prerelease: false
          files: release/